mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level.com.example.demo.dao: debug
spring:
  datasource:
    url: jdbc:mysql://47.94.105.130:3306/spring-security?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: ZHAODONGqwe123!@#
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    suffix: .html
  redis:
    host: localhost
    port: 6379
  resources:
    cache:
      cachecontrol:
        max-age: 60
server:
  port: 8081
#  servlet:
#    context-path: /server
